name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: projectserum-anchor-0.24.2
    container: projectserum/build:v0.24.2

    steps:
      - uses: actions/checkout@v3
      - name: Install libudev-dev
      - name: Build
        run: export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH" && anchor build
      - name: Run tests
        run: export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH" && anchor test
