name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install libudev-dev
        run: sudo apt update && sudo apt install libudev-dev
      - name: Install solana
        run: sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
      - name: Export solana path
        run: export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
      - name: Install AVM
        run: cargo install --git https://github.com/project-serum/anchor avm --force
      - name: Install Anchor
        run: avm install 0.24.2 && avm use 0.24.2
      - name: Build
        run: anchor build
      - name: Run tests
        run: anchor test
